# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

group :development do
  gem 'rspec', '~> 3.8'

  gem 'rspec-its', '~> 1.2'

  gem 'rspec-collection_matchers', '~> 1.1'
end
